In [1]:
#import nessary  modules for data  processing
import pandas as pd 
from sklearn.model_selection import train_test_split
import numpy as np

import matplotlib.pyplot as plt    
import seaborn as sns

In [5]:
#Get the dataset from github
github_csv_url = 'https://raw.githubusercontent.com/speedy-insect/Nyayo-Embakasi-climate-report/main/DATA/Nyayo%20Embakasi.csv'

#Read the dataset
df = pd.read_csv(github_csv_url)
# get a grips of the data
df.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,2388059,"Nyayo Embakasi, Nairobi",temperature,28.0,c,2024-02-06T05:00:00+00:00,2024-02-06T08:00:00+03:00,Africa/Nairobi,-1.304011,36.907681,NaN,NaN,NaN,AirGradient,AirGradient
1,2388059,"Nyayo Embakasi, Nairobi",temperature,27.0,c,2024-02-06T06:00:00+00:00,2024-02-06T09:00:00+03:00,Africa/Nairobi,-1.304011,36.907681,NaN,NaN,NaN,AirGradient,AirGradient
2,2388059,"Nyayo Embakasi, Nairobi",temperature,27.0,c,2024-02-06T07:00:00+00:00,2024-02-06T10:00:00+03:00,Africa/Nairobi,-1.304011,36.907681,NaN,NaN,NaN,AirGradient,AirGradient
3,2388059,"Nyayo Embakasi, Nairobi",temperature,27.0,c,2024-02-06T08:00:00+00:00,2024-02-06T11:00:00+03:00,Africa/Nairobi,-1.304011,36.907681,NaN,NaN,NaN,AirGradient,AirGradient
4,2388059,"Nyayo Embakasi, Nairobi",temperature,27.0,c,2024-02-06T10:00:00+00:00,2024-02-06T13:00:00+03:00,Africa/Nairobi,-1.304011,36.907681,NaN,NaN,NaN,AirGradient,AirGradient

In [3]:
#Conduct basic data inspection and cleaning of the data set